name: Mirror to OnThePixel-net/PixelBot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push to mirror repository
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          echo -e "## Mirror Repository\n\nThis is a mirror of [Paranoia8972/PixelBot](https://github.com/Paranoia8972/PixelBot). Please report issues and open pull requests there.\n\n$(cat README.md)" > README.md

          git add README.md
          git commit -m "Update README.md to indicate mirror repository"

          git remote add mirror https://github.com/OnThePixel-net/PixelBot.git
          git push mirror main

          echo "::notice::Successfully mirrored repository to OnThePixel-net/PixelBot"
