name: Push to OnThePIxel-net/PixelBot

on:
  push:
    branches:
      - main

jobs:
  push-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Push code to OnThePIxel-net/PixelBot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://github.com/OnThePIxel-net/PixelBot.git
          cd PixelBot
          git remote rm origin
          git remote add origin https://github.com/OnThePIxel-net/PixelBot.git
          git push origin main --force
